// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "image_weapons.h"

/////////////////////////////////////////////////////////////////////////////
// CImage_weapons

IMPLEMENT_DYNCREATE(CImage_weapons, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CImage_weapons properties

/////////////////////////////////////////////////////////////////////////////
// CImage_weapons operations
